name: catalog_to_xpublish
channels:
  - conda-forge
  - nodefaults

# a minimal environment for Catalog-To-Xpublish
dependencies:
  - python =3.11

  # For data processing
  - xarray
  - dask

  # For catalog access
  - intake
  - intake-xarray
  - pystac

  # For API access and data formats
  - fsspec
  - s3fs
  - h5netcdf
  - zarr

  # Dev tools: Language Server Protocol (LSP) (Optional), for:
  - python-lsp-server # LSP extension for Python (pylsp), including:
  - pylsp-mypy  # MyPy type checking for Python >=3.7.

  # Package management
  - conda
  - conda-build
  - conda-libmamba-solver
  - pip

  # we get the latest version of xpublish from github
  - pip:
    - git+https://github.com/xpublish-community/xpublish.git
